const fonts = {
  Bold: 'Roboto-Bold',
  Regular: 'Roboto-Regular',
  Thin: 'Roboto-Thin',
  Medium: 'Roboto-Medium',
  Light: 'Roboto-Light',
};

const Colors = {
  main: '#50c2f3',
  white: '#fff',
  black: '#000',
  yellow: '#FFFF00',
  gray: '#808080',
  bahama: '#1e4e79',
  graish: '#7a7a7a',
  midnight_blue: '#102C57',
  pearl_lusta: '#EADBC8',
  pearl_lustadark: '#DAC0A3',
  // white: '#FFF7E3',
  midblack: '#1C1C28',
};
const images = {
  englishflag: require('../assets/englishflag.png'),
  pakflag: require('../assets/pakflag.png'),
  indiaflag: require('../assets/indiaflag.png'),
  chinaflag: require('../assets/chinaflag.png'),
  select: require('../assets/selectphoto.png'),
  logo: require('../assets/logo.png'),
  home: require('../assets/home.png'),
  user: require('../assets/user.png'),
  logout: require('../assets/logout.png'),
  calculator: require('../assets/calculator.png'),
  prop1: require('../assets/prop1.jpg'),
  prop2: require('../assets/prop2.jpg'),
  prop3: require('../assets/prop3.jpg'),
  pro: require('../assets/pro.jpg'),
  agents: require('../assets/agents.png'),
  news: require('../assets/news.png'),
  lock: require('../assets/lock.png'),
  heart: require('../assets/heart.png'),
  support: require('../assets/support.png'),
  chat: require('../assets/chat.png'),
  info: require('../assets/info.png'),
  file: require('../assets/file.png'),
  term: require('../assets/term.png'),
  folder: require('../assets/folder.png'),
  share: require('../assets/share.png'),
  add: require('../assets/add.png'),
  addimage: require('../assets/addimage.png'),
  image1: require('../assets/image1.png'),
  image2: require('../assets/image2.png'),
  image3: require('../assets/image3.png'),
  addnew: require('../assets/addnew.png'),
  floorplan: require('../assets/floorplan.jpg'),
  login: require('../assets/login.png'),
  most: require('../assets/most.png'),
  hot: require('../assets/hot.png'),
  fav: require('../assets/fav.png'),
  log: require('../assets/log.png'),
  contactmail: require('../assets/contactmail.png'),
  msgs: require('../assets/msgs.png'),
  opnlock: require('../assets/opnlock.png'),
  srch: require('../assets/srch.png'),

  agentsicon: require('../assets/agentsicon.png'),
  cal: require('../assets/cal.png'),
  clisting: require('../assets/clisting.png'),
  mainhome: require('../assets/mainhome.png'),
  latestnews: require('../assets/latestnews.png'),
  hot2: require('../assets/hot2.png'),
  mvprop: require('../assets/mvprop.png'),
  ptype: require('../assets/ptype.png'),
  affil: require('../assets/affil.png'),
  shre: require('../assets/shre.png'),
  shareIcons: require('../assets/shareIcons.png'),

  user1: require('../assets/user1.png'),
  building: require('../assets/building.png'),
  plus: require('../assets/plus.png'),
  invoice: require('../assets/invoice.png'),
  blankImage: require('../assets/Blankimage.png'),
  More: require('../assets/More.png'),
  search: require('../assets/search.png'),
  
  beach: require('../assets/beach.jpg'),
  


  agentprofile: require('../assets/agentprofile.jpg'),
  map: require('../assets/map.jpg'),
  2: require('../assets/2.jpeg'),
  3: require('../assets/3.jpeg'),
  4: require('../assets/4.jpeg'),
  6: require('../assets/6.jpeg'),
  7: require('../assets/7.jpeg'),
  8: require('../assets/8.jpeg'),
  9: require('../assets/9.jpeg'),
  10: require('../assets/10.jpeg'),
  11: require('../assets/11.jpeg'),
  hot1: require('../assets/hot1.jpeg'),

};
export {fonts, Colors, images};
